#
# Autogenerated by Thrift Compiler (0.8.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#


class UserProfile
  include ::Thrift::Struct, ::Thrift::Struct_Union
  UID = 1
  NAME = 2
  BLURB = 3

  FIELDS = {
    UID => {:type => ::Thrift::Types::I32, :name => 'uid'},
    NAME => {:type => ::Thrift::Types::STRING, :name => 'name'},
    BLURB => {:type => ::Thrift::Types::STRING, :name => 'blurb'}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

